### ISSUE TITLE
[Trouble to Execute Siard Suite] MySQL 8.0.30 andSIARD-Suite-2.2.136-win

### ISSUE THREAD

**Issue by likeba** [sfa-siard/siard-suite#65]
Hello!

I have installed SIARD-Suite-2.2.136-win-exe.exe and tested 'Archive' fuction with MySQL 8.0.30 with attached '**simple DB.sql**'.

I had a similar problem in the previous SIARD-Suite, and t crashed with the following (ERROR).

I used to be able to avoid this by unchecking the "Meta data only" checkbox and checking "Archive views as tables" checkbox as shown in attached '**previousConfig.png**'.

However, in this version of SIARD Suite, there is no such checkbox.

The error occurs in the following environment, and the detailed error is attached as a picture.

(ERROR)
DBMS : MySQL 8.0.3 for Windows (MySQL Workbench 8.0.34)
DB to archive: test.sql (attached)
ERROR : **error.png**, **log.txt**
Settings to archive in SIARD Suite: 
  - DataServer: 127.0.0.1
  - PortNumber: 3306
  - Username : testuser(privilege: privilege.png)
  - Database name: library
  - Connection URL : jdbc:mysql://[127.0.0.1:3306/library?zeroDateTimeBehavior=convert_To_Null&characterEncoding=UTF-8&serverTimezone=UTC

![error](https://github.com/sfa-siard/siard-suite/assets/13463252/8c4ceabc-8bee-42cd-9cba-f809eb7ef36b)
[log.txt](https://github.com/sfa-siard/siard-suite/files/13232985/log.txt)
[MySQL.txt](https://github.com/sfa-siard/siard-suite/files/13232986/MySQL.txt)
![previousConfig](https://github.com/sfa-siard/siard-suite/assets/13463252/f241995d-4702-4595-9fc6-4655ec002c20)
![privilege](https://github.com/sfa-siard/siard-suite/assets/13463252/01951ee0-5a8c-470f-aa46-848f84d31405)

**Comment by sdbuehlmann** [comment]
Hi @likeba, thank you for your detailed report. We will look into that and get back to you. Thanks for your patience.

**Comment by mburri** [comment]
@likeba 
There are some known issues with newer versions of MySql that we need to address.
The two options you mentioned ("Export metadata only" and "Export views as tables") are still available, but they are now on the "Edit metadata" screen, as shown below:

![image](https://github.com/sfa-siard/siard-suite/assets/4577216/7184d672-ed13-4ea9-968f-8c71b38972fd)

Do you even get to this screen or does the error occur immediately?

I tried to reproduce the problem with MySQL 8.0.27 and was able to successfully archive the database with your test.sql: [test.zip](https://github.com/sfa-siard/siard-suite/files/13235573/test.zip)

However, I was using MySql 8.0.27 on Linux in a Docker setup. For some unknown reason, I was not able to set up an environment with MySQL 8.0.3 - there seem to be some major changes there. We need to figure this out.

In the meantime, when you get to the metadata screen, try checking the options as shown above. Checking "Archive views as tables" will probably have no effect, since your database actually has no views.

Or you could downgrade to MySQL 8.0.27 or even migrate to MariaDB if that is an option.

**Comment by likeba** [comment]
Hi~ @mburri 

First, I'll answer your question, and then show you a screen capture of how the error occurred. 

Do you even get to this screen or does the error occur immediately?
-> In the '② Connection' step, when I entered the database connection information and clicked the 'Next' button, an error occurred. I cannnot get to the screeen that you showd. The screen seams to be the screen of the '④ Metadata'.

The error process is as follows:

(1) Create a DB in MySQL 8.0.30 using test.sql.
(2) Execute SIARD SUITE , select '**Archive**' in [Archive, Open, Upload,  Export], click '**+Use new connection**', and select 'MySQL'.
(3) At the '② Connection' step, enter your connection information and click 'Next', as shown below. 
![Connection](https://github.com/sfa-siard/siard-suite/assets/13463252/e37f9449-d3d2-431e-8683-9c024fe82a19)
(4) Immediately after click, I got the error screen pictured below. 
![after Next in Connection](https://github.com/sfa-siard/siard-suite/assets/13463252/69270e74-8bb7-495a-96bb-feb87f3ff4be)


I strongly encourage you to test on windows 11. 
I'll try it on linux too.
If you can give me the specs of your linux version, I'll try to verify it.
